export const SET_QUESTIONS = "SET_QUESTIONS";

export const SET_CURRENT_QUESTION_ID = "SET_CURRENT_QUESTION_ID";

export const ADD_RESPONSE = "ADD_RESPONSE";

export const CHANGE_CURRENT_VIEW = "CHANGE_CURRENT_VIEW";